# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Nightly

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

env:
  DEBIAN_FRONTEND: 'noninteractive'
  TZ: Etc/UTC
  IMAGE_NAME: nan/nan
  GH_RUNNER: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'
      
      - name: Checkout branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.target }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:nightly .
      
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:nightly
      
      - name: Set success
        run: |
          echo 'GH_RUNNER="true"' >> ${GITHUB_ENV}

  build-fallback:
    runs-on: self-hosted
    timeout-minutes: 345600
    needs: [build]
    if: failure()

    steps:
      - name: Checkout branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.target }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:nightly .
      
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}:nightly

  publish:
    runs-on: ubuntu-latest
    needs: [build, build-fallback]
    if: ${{ (needs.build.result == 'success' && github.event_name != 'workflow_run') || (needs.build.result == 'failure' && needs.build-fallback.result == 'success') }}
    steps:
      - name: Publish release
        uses: notpeelz/action-gh-create-release@v5.0.1
        with:
          target: ${{ inputs.target }}
          tag: nightly
          prerelease: true
          strategy: replace
          title: "Automatic build"
          body: "Automatic build"
